// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dhiraj.jmxweb.model;

import com.dhiraj.jmxweb.model.JobUser;
import com.dhiraj.jmxweb.model.JobUserDataOnDemand;
import com.dhiraj.jmxweb.model.JobUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobUserIntegrationTest: @Transactional;
    
    @Autowired
    private JobUserDataOnDemand JobUserIntegrationTest.dod;
    
    @Test
    public void JobUserIntegrationTest.testCountJobUsers() {
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", dod.getRandomJobUser());
        long count = JobUser.countJobUsers();
        Assert.assertTrue("Counter for 'JobUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobUserIntegrationTest.testFindJobUser() {
        JobUser obj = dod.getRandomJobUser();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to provide an identifier", id);
        obj = JobUser.findJobUser(id);
        Assert.assertNotNull("Find method for 'JobUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JobUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobUserIntegrationTest.testFindAllJobUsers() {
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", dod.getRandomJobUser());
        long count = JobUser.countJobUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'JobUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JobUser> result = JobUser.findAllJobUsers();
        Assert.assertNotNull("Find all method for 'JobUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JobUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobUserIntegrationTest.testFindJobUserEntries() {
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", dod.getRandomJobUser());
        long count = JobUser.countJobUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JobUser> result = JobUser.findJobUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JobUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JobUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobUserIntegrationTest.testFlush() {
        JobUser obj = dod.getRandomJobUser();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to provide an identifier", id);
        obj = JobUser.findJobUser(id);
        Assert.assertNotNull("Find method for 'JobUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJobUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JobUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobUserIntegrationTest.testMergeUpdate() {
        JobUser obj = dod.getRandomJobUser();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to provide an identifier", id);
        obj = JobUser.findJobUser(id);
        boolean modified =  dod.modifyJobUser(obj);
        Integer currentVersion = obj.getVersion();
        JobUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JobUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", dod.getRandomJobUser());
        JobUser obj = dod.getNewTransientJobUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JobUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JobUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JobUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobUserIntegrationTest.testRemove() {
        JobUser obj = dod.getRandomJobUser();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobUser' failed to provide an identifier", id);
        obj = JobUser.findJobUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JobUser' with identifier '" + id + "'", JobUser.findJobUser(id));
    }
    
}
