// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dhiraj.jmxweb.model;

import com.dhiraj.jmxweb.model.JobUserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JobUserIntegrationTest_Roo_Configurable {
    
    declare @type: JobUserIntegrationTest: @Configurable;
    
}
