// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dhiraj.jmxweb.model;

import com.dhiraj.jmxweb.model.JobUser;
import com.dhiraj.jmxweb.model.JobUserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JobUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JobUserDataOnDemand: @Component;
    
    private Random JobUserDataOnDemand.rnd = new SecureRandom();
    
    private List<JobUser> JobUserDataOnDemand.data;
    
    public JobUser JobUserDataOnDemand.getNewTransientJobUser(int index) {
        JobUser obj = new JobUser();
        setAge(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JobUserDataOnDemand.setAge(JobUser obj, int index) {
        String age = "age_" + index;
        obj.setAge(age);
    }
    
    public void JobUserDataOnDemand.setName(JobUser obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JobUser JobUserDataOnDemand.getSpecificJobUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JobUser obj = data.get(index);
        Long id = obj.getId();
        return JobUser.findJobUser(id);
    }
    
    public JobUser JobUserDataOnDemand.getRandomJobUser() {
        init();
        JobUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JobUser.findJobUser(id);
    }
    
    public boolean JobUserDataOnDemand.modifyJobUser(JobUser obj) {
        return false;
    }
    
    public void JobUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JobUser.findJobUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JobUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JobUser>();
        for (int i = 0; i < 10; i++) {
            JobUser obj = getNewTransientJobUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
